// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "mac_vivado_dma64_w32_compute.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic mac_vivado_dma64_w32_compute::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic mac_vivado_dma64_w32_compute::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> mac_vivado_dma64_w32_compute::ap_ST_fsm_state1 = "1";
const sc_lv<8> mac_vivado_dma64_w32_compute::ap_ST_fsm_state2 = "10";
const sc_lv<8> mac_vivado_dma64_w32_compute::ap_ST_fsm_state3 = "100";
const sc_lv<8> mac_vivado_dma64_w32_compute::ap_ST_fsm_state4 = "1000";
const sc_lv<8> mac_vivado_dma64_w32_compute::ap_ST_fsm_state5 = "10000";
const sc_lv<8> mac_vivado_dma64_w32_compute::ap_ST_fsm_state6 = "100000";
const sc_lv<8> mac_vivado_dma64_w32_compute::ap_ST_fsm_state7 = "1000000";
const sc_lv<8> mac_vivado_dma64_w32_compute::ap_ST_fsm_state8 = "10000000";
const sc_lv<32> mac_vivado_dma64_w32_compute::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> mac_vivado_dma64_w32_compute::ap_const_lv32_1 = "1";
const sc_lv<32> mac_vivado_dma64_w32_compute::ap_const_lv32_2 = "10";
const sc_lv<1> mac_vivado_dma64_w32_compute::ap_const_lv1_0 = "0";
const sc_lv<32> mac_vivado_dma64_w32_compute::ap_const_lv32_4 = "100";
const sc_lv<1> mac_vivado_dma64_w32_compute::ap_const_lv1_1 = "1";
const sc_lv<32> mac_vivado_dma64_w32_compute::ap_const_lv32_5 = "101";
const sc_lv<32> mac_vivado_dma64_w32_compute::ap_const_lv32_6 = "110";
const sc_lv<32> mac_vivado_dma64_w32_compute::ap_const_lv32_7 = "111";
const sc_lv<32> mac_vivado_dma64_w32_compute::ap_const_lv32_3 = "11";
const sc_lv<13> mac_vivado_dma64_w32_compute::ap_const_lv13_0 = "0000000000000";
const sc_lv<32> mac_vivado_dma64_w32_compute::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<32> mac_vivado_dma64_w32_compute::ap_const_lv32_1F = "11111";
const sc_lv<32> mac_vivado_dma64_w32_compute::ap_const_lv32_1900 = "1100100000000";
const sc_lv<13> mac_vivado_dma64_w32_compute::ap_const_lv13_1900 = "1100100000000";
const sc_lv<32> mac_vivado_dma64_w32_compute::ap_const_lv32_C = "1100";
const sc_lv<32> mac_vivado_dma64_w32_compute::ap_const_lv32_FFFFE700 = "11111111111111111110011100000000";
const sc_lv<13> mac_vivado_dma64_w32_compute::ap_const_lv13_2 = "10";
const bool mac_vivado_dma64_w32_compute::ap_const_boolean_1 = true;

mac_vivado_dma64_w32_compute::mac_vivado_dma64_w32_compute(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_acc_fu_355_p2);
    sensitive << ( mul_ln95_reg_528 );
    sensitive << ( acc_0_i_fu_58 );

    SC_METHOD(thread_add_ln73_fu_227_p2);
    sensitive << ( in_rem_2_fu_223_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( mac_vec_empty_n );
    sensitive << ( mac_len_empty_n );
    sensitive << ( mac_vec_out_full_n );
    sensitive << ( mac_len_out_full_n );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln86_fu_292_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln86_fu_292_p2 );

    SC_METHOD(thread_i_1_fu_420_p2);
    sensitive << ( i1_0_i_reg_201 );

    SC_METHOD(thread_i_fu_250_p2);
    sensitive << ( i_0_i_reg_180 );

    SC_METHOD(thread_icmp_ln100_fu_368_p2);
    sensitive << ( mac_len_read_reg_431 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( vector_index_fu_362_p2 );

    SC_METHOD(thread_icmp_ln75_fu_245_p2);
    sensitive << ( length_reg_442 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_0_i_reg_180 );

    SC_METHOD(thread_icmp_ln86_fu_292_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( in_rem_0_i_reg_191 );

    SC_METHOD(thread_icmp_ln89_fu_298_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln86_fu_292_p2 );
    sensitive << ( in_rem_0_i_reg_191 );

    SC_METHOD(thread_icmp_ln92_fu_316_p2);
    sensitive << ( in_len_reg_505 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( i1_0_i_reg_201 );

    SC_METHOD(thread_in_len_fu_308_p3);
    sensitive << ( icmp_ln89_fu_298_p2 );
    sensitive << ( trunc_ln86_fu_304_p1 );

    SC_METHOD(thread_in_rem_2_fu_223_p2);
    sensitive << ( mac_vec_read_reg_426 );
    sensitive << ( mac_len_read_reg_431 );

    SC_METHOD(thread_in_rem_fu_337_p2);
    sensitive << ( in_rem_0_i_reg_191 );

    SC_METHOD(thread_length_fu_239_p2);
    sensitive << ( or_ln73_fu_233_p2 );

    SC_METHOD(thread_lshr_ln180_1_fu_390_p4);
    sensitive << ( vector_number_1_fu_62 );

    SC_METHOD(thread_lshr_ln1_fu_321_p4);
    sensitive << ( i1_0_i_reg_201 );

    SC_METHOD(thread_lshr_ln_fu_260_p4);
    sensitive << ( i_0_i_reg_180 );

    SC_METHOD(thread_mac_len_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mac_len_empty_n );

    SC_METHOD(thread_mac_len_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mac_len_out_full_n );

    SC_METHOD(thread_mac_len_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mac_vec_empty_n );
    sensitive << ( mac_len_dout );
    sensitive << ( mac_len_empty_n );
    sensitive << ( mac_vec_out_full_n );
    sensitive << ( mac_len_out_full_n );

    SC_METHOD(thread_mac_len_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mac_vec_empty_n );
    sensitive << ( mac_len_empty_n );
    sensitive << ( mac_vec_out_full_n );
    sensitive << ( mac_len_out_full_n );

    SC_METHOD(thread_mac_len_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mac_vec_empty_n );
    sensitive << ( mac_len_empty_n );
    sensitive << ( mac_vec_out_full_n );
    sensitive << ( mac_len_out_full_n );

    SC_METHOD(thread_mac_vec_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mac_vec_empty_n );

    SC_METHOD(thread_mac_vec_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mac_vec_out_full_n );

    SC_METHOD(thread_mac_vec_out_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mac_vec_dout );
    sensitive << ( mac_vec_empty_n );
    sensitive << ( mac_len_empty_n );
    sensitive << ( mac_vec_out_full_n );
    sensitive << ( mac_len_out_full_n );

    SC_METHOD(thread_mac_vec_out_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mac_vec_empty_n );
    sensitive << ( mac_len_empty_n );
    sensitive << ( mac_vec_out_full_n );
    sensitive << ( mac_len_out_full_n );

    SC_METHOD(thread_mac_vec_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mac_vec_empty_n );
    sensitive << ( mac_len_empty_n );
    sensitive << ( mac_vec_out_full_n );
    sensitive << ( mac_len_out_full_n );

    SC_METHOD(thread_mul_ln95_fu_343_p0);
    sensitive << ( p_inbuff_1_V_q0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_mul_ln95_fu_343_p1);
    sensitive << ( p_inbuff_0_V_q0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_mul_ln95_fu_343_p2);
    sensitive << ( mul_ln95_fu_343_p0 );
    sensitive << ( mul_ln95_fu_343_p1 );

    SC_METHOD(thread_or_ln73_fu_233_p2);
    sensitive << ( add_ln73_fu_227_p2 );

    SC_METHOD(thread_p_inbuff_0_V_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln180_fu_270_p1 );
    sensitive << ( zext_ln215_fu_331_p1 );

    SC_METHOD(thread_p_inbuff_0_V_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_p_inbuff_1_V_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln180_fu_270_p1 );
    sensitive << ( zext_ln215_fu_331_p1 );

    SC_METHOD(thread_p_inbuff_1_V_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_p_outbuff_0_V_address0);
    sensitive << ( p_outbuff_0_V_addr_reg_470 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln180_1_fu_400_p1 );

    SC_METHOD(thread_p_outbuff_0_V_ce0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_p_outbuff_0_V_d0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( acc_fu_355_p2 );
    sensitive << ( select_ln180_fu_283_p3 );

    SC_METHOD(thread_p_outbuff_0_V_we0);
    sensitive << ( trunc_ln180_reg_455 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln100_fu_368_p2 );
    sensitive << ( trunc_ln180_1_fu_386_p1 );

    SC_METHOD(thread_p_outbuff_1_V_address0);
    sensitive << ( p_outbuff_1_V_addr_reg_475 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln180_1_fu_400_p1 );

    SC_METHOD(thread_p_outbuff_1_V_ce0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_p_outbuff_1_V_d0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( acc_fu_355_p2 );
    sensitive << ( select_ln180_fu_283_p3 );

    SC_METHOD(thread_p_outbuff_1_V_we0);
    sensitive << ( trunc_ln180_reg_455 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln100_fu_368_p2 );
    sensitive << ( trunc_ln180_1_fu_386_p1 );

    SC_METHOD(thread_select_ln180_fu_283_p3);
    sensitive << ( p_inbuff_0_V_q0 );
    sensitive << ( p_inbuff_1_V_q0 );
    sensitive << ( trunc_ln180_reg_455 );

    SC_METHOD(thread_trunc_ln180_1_fu_386_p1);
    sensitive << ( vector_number_1_fu_62 );

    SC_METHOD(thread_trunc_ln180_fu_256_p1);
    sensitive << ( i_0_i_reg_180 );

    SC_METHOD(thread_trunc_ln86_fu_304_p1);
    sensitive << ( in_rem_0_i_reg_191 );

    SC_METHOD(thread_vector_index_fu_362_p2);
    sensitive << ( vector_index_1_fu_66 );

    SC_METHOD(thread_vector_number_fu_409_p2);
    sensitive << ( vector_number_1_fu_62 );

    SC_METHOD(thread_zext_ln180_1_fu_400_p1);
    sensitive << ( lshr_ln180_1_fu_390_p4 );

    SC_METHOD(thread_zext_ln180_fu_270_p1);
    sensitive << ( lshr_ln_fu_260_p4 );

    SC_METHOD(thread_zext_ln215_fu_331_p1);
    sensitive << ( lshr_ln1_fu_321_p4 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mac_vec_empty_n );
    sensitive << ( mac_len_empty_n );
    sensitive << ( mac_vec_out_full_n );
    sensitive << ( mac_len_out_full_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln75_fu_245_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln86_fu_292_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln92_fu_316_p2 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "00000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "mac_vivado_dma64_w32_compute_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, p_inbuff_0_V_address0, "(port)p_inbuff_0_V_address0");
    sc_trace(mVcdFile, p_inbuff_0_V_ce0, "(port)p_inbuff_0_V_ce0");
    sc_trace(mVcdFile, p_inbuff_0_V_q0, "(port)p_inbuff_0_V_q0");
    sc_trace(mVcdFile, p_inbuff_1_V_address0, "(port)p_inbuff_1_V_address0");
    sc_trace(mVcdFile, p_inbuff_1_V_ce0, "(port)p_inbuff_1_V_ce0");
    sc_trace(mVcdFile, p_inbuff_1_V_q0, "(port)p_inbuff_1_V_q0");
    sc_trace(mVcdFile, mac_vec_dout, "(port)mac_vec_dout");
    sc_trace(mVcdFile, mac_vec_empty_n, "(port)mac_vec_empty_n");
    sc_trace(mVcdFile, mac_vec_read, "(port)mac_vec_read");
    sc_trace(mVcdFile, mac_len_dout, "(port)mac_len_dout");
    sc_trace(mVcdFile, mac_len_empty_n, "(port)mac_len_empty_n");
    sc_trace(mVcdFile, mac_len_read, "(port)mac_len_read");
    sc_trace(mVcdFile, p_outbuff_0_V_address0, "(port)p_outbuff_0_V_address0");
    sc_trace(mVcdFile, p_outbuff_0_V_ce0, "(port)p_outbuff_0_V_ce0");
    sc_trace(mVcdFile, p_outbuff_0_V_we0, "(port)p_outbuff_0_V_we0");
    sc_trace(mVcdFile, p_outbuff_0_V_d0, "(port)p_outbuff_0_V_d0");
    sc_trace(mVcdFile, p_outbuff_1_V_address0, "(port)p_outbuff_1_V_address0");
    sc_trace(mVcdFile, p_outbuff_1_V_ce0, "(port)p_outbuff_1_V_ce0");
    sc_trace(mVcdFile, p_outbuff_1_V_we0, "(port)p_outbuff_1_V_we0");
    sc_trace(mVcdFile, p_outbuff_1_V_d0, "(port)p_outbuff_1_V_d0");
    sc_trace(mVcdFile, mac_vec_out_din, "(port)mac_vec_out_din");
    sc_trace(mVcdFile, mac_vec_out_full_n, "(port)mac_vec_out_full_n");
    sc_trace(mVcdFile, mac_vec_out_write, "(port)mac_vec_out_write");
    sc_trace(mVcdFile, mac_len_out_din, "(port)mac_len_out_din");
    sc_trace(mVcdFile, mac_len_out_full_n, "(port)mac_len_out_full_n");
    sc_trace(mVcdFile, mac_len_out_write, "(port)mac_len_out_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, mac_vec_blk_n, "mac_vec_blk_n");
    sc_trace(mVcdFile, mac_len_blk_n, "mac_len_blk_n");
    sc_trace(mVcdFile, mac_vec_out_blk_n, "mac_vec_out_blk_n");
    sc_trace(mVcdFile, mac_len_out_blk_n, "mac_len_out_blk_n");
    sc_trace(mVcdFile, mac_vec_read_reg_426, "mac_vec_read_reg_426");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, mac_len_read_reg_431, "mac_len_read_reg_431");
    sc_trace(mVcdFile, in_rem_2_fu_223_p2, "in_rem_2_fu_223_p2");
    sc_trace(mVcdFile, in_rem_2_reg_437, "in_rem_2_reg_437");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, length_fu_239_p2, "length_fu_239_p2");
    sc_trace(mVcdFile, length_reg_442, "length_reg_442");
    sc_trace(mVcdFile, i_fu_250_p2, "i_fu_250_p2");
    sc_trace(mVcdFile, i_reg_450, "i_reg_450");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, trunc_ln180_fu_256_p1, "trunc_ln180_fu_256_p1");
    sc_trace(mVcdFile, trunc_ln180_reg_455, "trunc_ln180_reg_455");
    sc_trace(mVcdFile, icmp_ln75_fu_245_p2, "icmp_ln75_fu_245_p2");
    sc_trace(mVcdFile, p_outbuff_0_V_addr_reg_470, "p_outbuff_0_V_addr_reg_470");
    sc_trace(mVcdFile, p_outbuff_1_V_addr_reg_475, "p_outbuff_1_V_addr_reg_475");
    sc_trace(mVcdFile, in_len_fu_308_p3, "in_len_fu_308_p3");
    sc_trace(mVcdFile, in_len_reg_505, "in_len_reg_505");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, icmp_ln86_fu_292_p2, "icmp_ln86_fu_292_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, icmp_ln92_fu_316_p2, "icmp_ln92_fu_316_p2");
    sc_trace(mVcdFile, in_rem_fu_337_p2, "in_rem_fu_337_p2");
    sc_trace(mVcdFile, mul_ln95_fu_343_p2, "mul_ln95_fu_343_p2");
    sc_trace(mVcdFile, mul_ln95_reg_528, "mul_ln95_reg_528");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, i_1_fu_420_p2, "i_1_fu_420_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, i_0_i_reg_180, "i_0_i_reg_180");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, in_rem_0_i_reg_191, "in_rem_0_i_reg_191");
    sc_trace(mVcdFile, i1_0_i_reg_201, "i1_0_i_reg_201");
    sc_trace(mVcdFile, zext_ln180_fu_270_p1, "zext_ln180_fu_270_p1");
    sc_trace(mVcdFile, zext_ln215_fu_331_p1, "zext_ln215_fu_331_p1");
    sc_trace(mVcdFile, zext_ln180_1_fu_400_p1, "zext_ln180_1_fu_400_p1");
    sc_trace(mVcdFile, icmp_ln100_fu_368_p2, "icmp_ln100_fu_368_p2");
    sc_trace(mVcdFile, acc_0_i_fu_58, "acc_0_i_fu_58");
    sc_trace(mVcdFile, acc_fu_355_p2, "acc_fu_355_p2");
    sc_trace(mVcdFile, vector_number_1_fu_62, "vector_number_1_fu_62");
    sc_trace(mVcdFile, vector_number_fu_409_p2, "vector_number_fu_409_p2");
    sc_trace(mVcdFile, vector_index_1_fu_66, "vector_index_1_fu_66");
    sc_trace(mVcdFile, vector_index_fu_362_p2, "vector_index_fu_362_p2");
    sc_trace(mVcdFile, select_ln180_fu_283_p3, "select_ln180_fu_283_p3");
    sc_trace(mVcdFile, trunc_ln180_1_fu_386_p1, "trunc_ln180_1_fu_386_p1");
    sc_trace(mVcdFile, add_ln73_fu_227_p2, "add_ln73_fu_227_p2");
    sc_trace(mVcdFile, or_ln73_fu_233_p2, "or_ln73_fu_233_p2");
    sc_trace(mVcdFile, lshr_ln_fu_260_p4, "lshr_ln_fu_260_p4");
    sc_trace(mVcdFile, icmp_ln89_fu_298_p2, "icmp_ln89_fu_298_p2");
    sc_trace(mVcdFile, trunc_ln86_fu_304_p1, "trunc_ln86_fu_304_p1");
    sc_trace(mVcdFile, lshr_ln1_fu_321_p4, "lshr_ln1_fu_321_p4");
    sc_trace(mVcdFile, mul_ln95_fu_343_p0, "mul_ln95_fu_343_p0");
    sc_trace(mVcdFile, mul_ln95_fu_343_p1, "mul_ln95_fu_343_p1");
    sc_trace(mVcdFile, lshr_ln180_1_fu_390_p4, "lshr_ln180_1_fu_390_p4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

mac_vivado_dma64_w32_compute::~mac_vivado_dma64_w32_compute() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void mac_vivado_dma64_w32_compute::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_368_p2.read()))) {
        acc_0_i_fu_58 = acc_fu_355_p2.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                 esl_seteq<1,1,1>(icmp_ln75_fu_245_p2.read(), ap_const_lv1_1)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln100_fu_368_p2.read())))) {
        acc_0_i_fu_58 = ap_const_lv32_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln86_fu_292_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        i1_0_i_reg_201 = i_1_fu_420_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(icmp_ln86_fu_292_p2.read(), ap_const_lv1_1))) {
        i1_0_i_reg_201 = ap_const_lv13_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_0_i_reg_180 = i_reg_450.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_0_i_reg_180 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln75_fu_245_p2.read(), ap_const_lv1_1))) {
        in_rem_0_i_reg_191 = in_rem_2_reg_437.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln92_fu_316_p2.read()))) {
        in_rem_0_i_reg_191 = in_rem_fu_337_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln100_fu_368_p2.read()))) {
        vector_index_1_fu_66 = vector_index_fu_362_p2.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                 esl_seteq<1,1,1>(icmp_ln75_fu_245_p2.read(), ap_const_lv1_1)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln100_fu_368_p2.read())))) {
        vector_index_1_fu_66 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln100_fu_368_p2.read()))) {
        vector_number_1_fu_62 = vector_number_fu_409_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(icmp_ln75_fu_245_p2.read(), ap_const_lv1_1))) {
        vector_number_1_fu_62 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_reg_450 = i_fu_250_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln86_fu_292_p2.read(), ap_const_lv1_1))) {
        in_len_reg_505 = in_len_fu_308_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        in_rem_2_reg_437 = in_rem_2_fu_223_p2.read();
        length_reg_442 = length_fu_239_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, mac_vec_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, mac_len_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, mac_vec_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, mac_len_out_full_n.read())))) {
        mac_len_read_reg_431 = mac_len_dout.read();
        mac_vec_read_reg_426 = mac_vec_dout.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        mul_ln95_reg_528 = mul_ln95_fu_343_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln75_fu_245_p2.read(), ap_const_lv1_0))) {
        p_outbuff_0_V_addr_reg_470 =  (sc_lv<6>) (zext_ln180_fu_270_p1.read());
        p_outbuff_1_V_addr_reg_475 =  (sc_lv<6>) (zext_ln180_fu_270_p1.read());
        trunc_ln180_reg_455 = trunc_ln180_fu_256_p1.read();
    }
}

void mac_vivado_dma64_w32_compute::thread_acc_fu_355_p2() {
    acc_fu_355_p2 = (!mul_ln95_reg_528.read().is_01() || !acc_0_i_fu_58.read().is_01())? sc_lv<32>(): (sc_biguint<32>(mul_ln95_reg_528.read()) + sc_biguint<32>(acc_0_i_fu_58.read()));
}

void mac_vivado_dma64_w32_compute::thread_add_ln73_fu_227_p2() {
    add_ln73_fu_227_p2 = (!in_rem_2_fu_223_p2.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_biguint<32>(in_rem_2_fu_223_p2.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void mac_vivado_dma64_w32_compute::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void mac_vivado_dma64_w32_compute::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void mac_vivado_dma64_w32_compute::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void mac_vivado_dma64_w32_compute::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void mac_vivado_dma64_w32_compute::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void mac_vivado_dma64_w32_compute::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void mac_vivado_dma64_w32_compute::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void mac_vivado_dma64_w32_compute::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void mac_vivado_dma64_w32_compute::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, mac_vec_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, mac_len_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, mac_vec_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, mac_len_out_full_n.read()));
}

void mac_vivado_dma64_w32_compute::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln86_fu_292_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void mac_vivado_dma64_w32_compute::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void mac_vivado_dma64_w32_compute::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln86_fu_292_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void mac_vivado_dma64_w32_compute::thread_i_1_fu_420_p2() {
    i_1_fu_420_p2 = (!i1_0_i_reg_201.read().is_01() || !ap_const_lv13_2.is_01())? sc_lv<13>(): (sc_biguint<13>(i1_0_i_reg_201.read()) + sc_biguint<13>(ap_const_lv13_2));
}

void mac_vivado_dma64_w32_compute::thread_i_fu_250_p2() {
    i_fu_250_p2 = (!i_0_i_reg_180.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(i_0_i_reg_180.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void mac_vivado_dma64_w32_compute::thread_icmp_ln100_fu_368_p2() {
    icmp_ln100_fu_368_p2 = (!vector_index_fu_362_p2.read().is_01() || !mac_len_read_reg_431.read().is_01())? sc_lv<1>(): sc_lv<1>(vector_index_fu_362_p2.read() == mac_len_read_reg_431.read());
}

void mac_vivado_dma64_w32_compute::thread_icmp_ln75_fu_245_p2() {
    icmp_ln75_fu_245_p2 = (!i_0_i_reg_180.read().is_01() || !length_reg_442.read().is_01())? sc_lv<1>(): sc_lv<1>(i_0_i_reg_180.read() == length_reg_442.read());
}

void mac_vivado_dma64_w32_compute::thread_icmp_ln86_fu_292_p2() {
    icmp_ln86_fu_292_p2 = (!in_rem_0_i_reg_191.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(in_rem_0_i_reg_191.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void mac_vivado_dma64_w32_compute::thread_icmp_ln89_fu_298_p2() {
    icmp_ln89_fu_298_p2 = (!in_rem_0_i_reg_191.read().is_01() || !ap_const_lv32_1900.is_01())? sc_lv<1>(): (sc_bigint<32>(in_rem_0_i_reg_191.read()) > sc_bigint<32>(ap_const_lv32_1900));
}

void mac_vivado_dma64_w32_compute::thread_icmp_ln92_fu_316_p2() {
    icmp_ln92_fu_316_p2 = (!i1_0_i_reg_201.read().is_01() || !in_len_reg_505.read().is_01())? sc_lv<1>(): (sc_biguint<13>(i1_0_i_reg_201.read()) < sc_biguint<13>(in_len_reg_505.read()));
}

void mac_vivado_dma64_w32_compute::thread_in_len_fu_308_p3() {
    in_len_fu_308_p3 = (!icmp_ln89_fu_298_p2.read()[0].is_01())? sc_lv<13>(): ((icmp_ln89_fu_298_p2.read()[0].to_bool())? ap_const_lv13_1900: trunc_ln86_fu_304_p1.read());
}

void mac_vivado_dma64_w32_compute::thread_in_rem_2_fu_223_p2() {
    in_rem_2_fu_223_p2 = (!mac_len_read_reg_431.read().is_01() || !mac_vec_read_reg_426.read().is_01())? sc_lv<32>(): sc_bigint<32>(mac_len_read_reg_431.read()) * sc_bigint<32>(mac_vec_read_reg_426.read());
}

void mac_vivado_dma64_w32_compute::thread_in_rem_fu_337_p2() {
    in_rem_fu_337_p2 = (!in_rem_0_i_reg_191.read().is_01() || !ap_const_lv32_FFFFE700.is_01())? sc_lv<32>(): (sc_biguint<32>(in_rem_0_i_reg_191.read()) + sc_bigint<32>(ap_const_lv32_FFFFE700));
}

void mac_vivado_dma64_w32_compute::thread_length_fu_239_p2() {
    length_fu_239_p2 = (!or_ln73_fu_233_p2.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(or_ln73_fu_233_p2.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void mac_vivado_dma64_w32_compute::thread_lshr_ln180_1_fu_390_p4() {
    lshr_ln180_1_fu_390_p4 = vector_number_1_fu_62.read().range(31, 1);
}

void mac_vivado_dma64_w32_compute::thread_lshr_ln1_fu_321_p4() {
    lshr_ln1_fu_321_p4 = i1_0_i_reg_201.read().range(12, 1);
}

void mac_vivado_dma64_w32_compute::thread_lshr_ln_fu_260_p4() {
    lshr_ln_fu_260_p4 = i_0_i_reg_180.read().range(31, 1);
}

void mac_vivado_dma64_w32_compute::thread_mac_len_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        mac_len_blk_n = mac_len_empty_n.read();
    } else {
        mac_len_blk_n = ap_const_logic_1;
    }
}

void mac_vivado_dma64_w32_compute::thread_mac_len_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        mac_len_out_blk_n = mac_len_out_full_n.read();
    } else {
        mac_len_out_blk_n = ap_const_logic_1;
    }
}

void mac_vivado_dma64_w32_compute::thread_mac_len_out_din() {
    mac_len_out_din = mac_len_dout.read();
}

void mac_vivado_dma64_w32_compute::thread_mac_len_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, mac_vec_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, mac_len_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, mac_vec_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, mac_len_out_full_n.read())))) {
        mac_len_out_write = ap_const_logic_1;
    } else {
        mac_len_out_write = ap_const_logic_0;
    }
}

void mac_vivado_dma64_w32_compute::thread_mac_len_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, mac_vec_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, mac_len_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, mac_vec_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, mac_len_out_full_n.read())))) {
        mac_len_read = ap_const_logic_1;
    } else {
        mac_len_read = ap_const_logic_0;
    }
}

void mac_vivado_dma64_w32_compute::thread_mac_vec_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        mac_vec_blk_n = mac_vec_empty_n.read();
    } else {
        mac_vec_blk_n = ap_const_logic_1;
    }
}

void mac_vivado_dma64_w32_compute::thread_mac_vec_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        mac_vec_out_blk_n = mac_vec_out_full_n.read();
    } else {
        mac_vec_out_blk_n = ap_const_logic_1;
    }
}

void mac_vivado_dma64_w32_compute::thread_mac_vec_out_din() {
    mac_vec_out_din = mac_vec_dout.read();
}

void mac_vivado_dma64_w32_compute::thread_mac_vec_out_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, mac_vec_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, mac_len_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, mac_vec_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, mac_len_out_full_n.read())))) {
        mac_vec_out_write = ap_const_logic_1;
    } else {
        mac_vec_out_write = ap_const_logic_0;
    }
}

void mac_vivado_dma64_w32_compute::thread_mac_vec_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, mac_vec_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, mac_len_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, mac_vec_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, mac_len_out_full_n.read())))) {
        mac_vec_read = ap_const_logic_1;
    } else {
        mac_vec_read = ap_const_logic_0;
    }
}

void mac_vivado_dma64_w32_compute::thread_mul_ln95_fu_343_p0() {
    mul_ln95_fu_343_p0 = p_inbuff_1_V_q0.read();
}

void mac_vivado_dma64_w32_compute::thread_mul_ln95_fu_343_p1() {
    mul_ln95_fu_343_p1 = p_inbuff_0_V_q0.read();
}

void mac_vivado_dma64_w32_compute::thread_mul_ln95_fu_343_p2() {
    mul_ln95_fu_343_p2 = (!mul_ln95_fu_343_p0.read().is_01() || !mul_ln95_fu_343_p1.read().is_01())? sc_lv<32>(): sc_bigint<32>(mul_ln95_fu_343_p0.read()) * sc_bigint<32>(mul_ln95_fu_343_p1.read());
}

void mac_vivado_dma64_w32_compute::thread_or_ln73_fu_233_p2() {
    or_ln73_fu_233_p2 = (add_ln73_fu_227_p2.read() | ap_const_lv32_1);
}

void mac_vivado_dma64_w32_compute::thread_p_inbuff_0_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        p_inbuff_0_V_address0 =  (sc_lv<12>) (zext_ln215_fu_331_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        p_inbuff_0_V_address0 =  (sc_lv<12>) (zext_ln180_fu_270_p1.read());
    } else {
        p_inbuff_0_V_address0 = "XXXXXXXXXXXX";
    }
}

void mac_vivado_dma64_w32_compute::thread_p_inbuff_0_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        p_inbuff_0_V_ce0 = ap_const_logic_1;
    } else {
        p_inbuff_0_V_ce0 = ap_const_logic_0;
    }
}

void mac_vivado_dma64_w32_compute::thread_p_inbuff_1_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        p_inbuff_1_V_address0 =  (sc_lv<12>) (zext_ln215_fu_331_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        p_inbuff_1_V_address0 =  (sc_lv<12>) (zext_ln180_fu_270_p1.read());
    } else {
        p_inbuff_1_V_address0 = "XXXXXXXXXXXX";
    }
}

void mac_vivado_dma64_w32_compute::thread_p_inbuff_1_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        p_inbuff_1_V_ce0 = ap_const_logic_1;
    } else {
        p_inbuff_1_V_ce0 = ap_const_logic_0;
    }
}

void mac_vivado_dma64_w32_compute::thread_p_outbuff_0_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        p_outbuff_0_V_address0 =  (sc_lv<6>) (zext_ln180_1_fu_400_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        p_outbuff_0_V_address0 = p_outbuff_0_V_addr_reg_470.read();
    } else {
        p_outbuff_0_V_address0 =  (sc_lv<6>) ("XXXXXX");
    }
}

void mac_vivado_dma64_w32_compute::thread_p_outbuff_0_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        p_outbuff_0_V_ce0 = ap_const_logic_1;
    } else {
        p_outbuff_0_V_ce0 = ap_const_logic_0;
    }
}

void mac_vivado_dma64_w32_compute::thread_p_outbuff_0_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        p_outbuff_0_V_d0 = acc_fu_355_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        p_outbuff_0_V_d0 = select_ln180_fu_283_p3.read();
    } else {
        p_outbuff_0_V_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void mac_vivado_dma64_w32_compute::thread_p_outbuff_0_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(trunc_ln180_reg_455.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln100_fu_368_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, trunc_ln180_1_fu_386_p1.read())))) {
        p_outbuff_0_V_we0 = ap_const_logic_1;
    } else {
        p_outbuff_0_V_we0 = ap_const_logic_0;
    }
}

void mac_vivado_dma64_w32_compute::thread_p_outbuff_1_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        p_outbuff_1_V_address0 =  (sc_lv<6>) (zext_ln180_1_fu_400_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        p_outbuff_1_V_address0 = p_outbuff_1_V_addr_reg_475.read();
    } else {
        p_outbuff_1_V_address0 =  (sc_lv<6>) ("XXXXXX");
    }
}

void mac_vivado_dma64_w32_compute::thread_p_outbuff_1_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        p_outbuff_1_V_ce0 = ap_const_logic_1;
    } else {
        p_outbuff_1_V_ce0 = ap_const_logic_0;
    }
}

void mac_vivado_dma64_w32_compute::thread_p_outbuff_1_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        p_outbuff_1_V_d0 = acc_fu_355_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        p_outbuff_1_V_d0 = select_ln180_fu_283_p3.read();
    } else {
        p_outbuff_1_V_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void mac_vivado_dma64_w32_compute::thread_p_outbuff_1_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
          esl_seteq<1,1,1>(trunc_ln180_reg_455.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln100_fu_368_p2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, trunc_ln180_1_fu_386_p1.read())))) {
        p_outbuff_1_V_we0 = ap_const_logic_1;
    } else {
        p_outbuff_1_V_we0 = ap_const_logic_0;
    }
}

void mac_vivado_dma64_w32_compute::thread_select_ln180_fu_283_p3() {
    select_ln180_fu_283_p3 = (!trunc_ln180_reg_455.read()[0].is_01())? sc_lv<32>(): ((trunc_ln180_reg_455.read()[0].to_bool())? p_inbuff_1_V_q0.read(): p_inbuff_0_V_q0.read());
}

void mac_vivado_dma64_w32_compute::thread_trunc_ln180_1_fu_386_p1() {
    trunc_ln180_1_fu_386_p1 = vector_number_1_fu_62.read().range(1-1, 0);
}

void mac_vivado_dma64_w32_compute::thread_trunc_ln180_fu_256_p1() {
    trunc_ln180_fu_256_p1 = i_0_i_reg_180.read().range(1-1, 0);
}

void mac_vivado_dma64_w32_compute::thread_trunc_ln86_fu_304_p1() {
    trunc_ln86_fu_304_p1 = in_rem_0_i_reg_191.read().range(13-1, 0);
}

void mac_vivado_dma64_w32_compute::thread_vector_index_fu_362_p2() {
    vector_index_fu_362_p2 = (!vector_index_1_fu_66.read().is_01() || !ap_const_lv32_2.is_01())? sc_lv<32>(): (sc_biguint<32>(vector_index_1_fu_66.read()) + sc_biguint<32>(ap_const_lv32_2));
}

void mac_vivado_dma64_w32_compute::thread_vector_number_fu_409_p2() {
    vector_number_fu_409_p2 = (!vector_number_1_fu_62.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(vector_number_1_fu_62.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void mac_vivado_dma64_w32_compute::thread_zext_ln180_1_fu_400_p1() {
    zext_ln180_1_fu_400_p1 = esl_zext<64,31>(lshr_ln180_1_fu_390_p4.read());
}

void mac_vivado_dma64_w32_compute::thread_zext_ln180_fu_270_p1() {
    zext_ln180_fu_270_p1 = esl_zext<64,31>(lshr_ln_fu_260_p4.read());
}

void mac_vivado_dma64_w32_compute::thread_zext_ln215_fu_331_p1() {
    zext_ln215_fu_331_p1 = esl_zext<64,12>(lshr_ln1_fu_321_p4.read());
}

void mac_vivado_dma64_w32_compute::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, mac_vec_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, mac_len_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, mac_vec_out_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, mac_len_out_full_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln75_fu_245_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln86_fu_292_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln92_fu_316_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<8>) ("XXXXXXXX");
            break;
    }
}

}

