#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("out_word_V_din", 64, hls_out, 0, "ap_fifo", "fifo_data", 1),
	Port_Property("out_word_V_full_n", 1, hls_in, 0, "ap_fifo", "fifo_status", 1),
	Port_Property("out_word_V_write", 1, hls_out, 0, "ap_fifo", "fifo_update", 1),
	Port_Property("in1_word_V_dout", 64, hls_in, 1, "ap_fifo", "fifo_data", 1),
	Port_Property("in1_word_V_empty_n", 1, hls_in, 1, "ap_fifo", "fifo_status", 1),
	Port_Property("in1_word_V_read", 1, hls_out, 1, "ap_fifo", "fifo_update", 1),
	Port_Property("conf_info_mac_n", 32, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("conf_info_mac_vec", 32, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("conf_info_mac_len", 32, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("load_ctrl", 96, hls_out, 5, "ap_hs", "out_data", 1),
	Port_Property("store_ctrl", 96, hls_out, 6, "ap_hs", "out_data", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("load_ctrl_ap_vld", 1, hls_out, 5, "ap_hs", "out_vld", 1),
	Port_Property("load_ctrl_ap_ack", 1, hls_in, 5, "ap_hs", "out_acc", 1),
	Port_Property("store_ctrl_ap_vld", 1, hls_out, 6, "ap_hs", "out_vld", 1),
	Port_Property("store_ctrl_ap_ack", 1, hls_in, 6, "ap_hs", "out_acc", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "top";
